name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  configure_helm:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: engineerd/configurator@v0.0.1
        with:
          name: "hb3"
          url: "https://get.helm.sh/helm-v3.0.0-beta.3-linux-amd64.tar.gz"
          pathInArchive: "linux-amd64/helm"
