name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  kind:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: downloading micro gateway
        run: |
          wget https://bintray.com/wso2/rpm/rpm -O bintray-wso2-rpm.repo
          ls
      - name: Testing
        run: |
          h3 --help
