name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  configurator:
    runs-on: ubuntu-latest
    steps:
    - name: configure Helm 3
      run: |
        export HELM_PLATFORM=linux-amd64 && export HELM_VERSION=helm-v3.0.0-alpha.2
        wget https://get.helm.sh/$HELM_VERSION-$HELM_PLATFORM.tar.gz
        tar -xvzf $HELM_VERSION-$HELM_PLATFORM.tar.gz
        rm -rf $HELM_VERSION-$HELM_PLATFORM.tar.gz
        mv $HELM_PLATFORM/helm <some-directory-in-path>/helm3
        chmod +x $GOBIN/helm3
