name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  kind:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download from Google Drive
        run: |
            wget https://drive.google.com/drive/folders/1hUlrP4M314vP0wIaK3wVQRIgfvANAr1t?usp=sharing
            ls
      - name: Testing
        run: |
            micro-gw --help
#https://drive.google.com/uc?export=download&id=
            
