name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  kind:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download from Google Drive
      - uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.CREDENTIALS }}
          download-from: /path/to/download
          download-to: ./

